### ISSUE TITLE
Error when player wins game, & my fix.

### ISSUE THREAD

**Issue by Nikorasu** [eliasffyksen/MiniSnakes#2]
When the player wins, by filling every space with snake, this error occurs because there's nowhere left to place the next food:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nik/PyProjects/SnakeAI/snake.py", line 16, in do
    pos_food = (snake == 0).flatten().to(t.float).multinomial(1)[0]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: invalid multinomial distribution (sum of probabilities <= 0)
```
The way I fixed it, was to alter lines 15-19:
https://github.com/eliasffyksen/MiniSnakes/blob/62a50443043321613b6b58f50b48145f18b61869/MiniSnakes.py#L15-L19
So they look like this instead:
```py
    if snake[tuple(pos_next)] != -1:
        snake[snake > 0] -= 1
    elif (snake == 0).any():
        pos_food = (snake == 0).flatten().to(t.float).multinomial(1)[0]
        snake[unravel(pos_food, snake.shape)] = -1
```
This way there is no error with eating the final food. Tho I'm not sure if that's necessarily the best alternative. It works for me, because [for my use](https://github.com/Nikorasu/SnakeAI), I've added a return at the end which calculates a reward for ML, and this enables me to reward for obtaining the last food and easily mark a win.

**Comment by Nikorasu** [comment]
Oh also, I'm less certain about this bug, but I think line 13:
https://github.com/eliasffyksen/MiniSnakes/blob/62a50443043321613b6b58f50b48145f18b61869/MiniSnakes.py#L13
Should be:
```py
if (snake[tuple(pos_next)] > 1).any():
```
That way, the snake can move where the tail was. Tho whether that is desired may depend on the use.
